name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, windows-2022, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run auditpol
      run: | 
        auditpol /list /subcategory:* /r
        auditpol /get /category:*
        Get-WinEvent -ListLog * | Select-Object LogName, MaximumSizeInBytes


