name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run auditpol
      run: | 
        auditpol /list /subcategory:* /r
        Get-WinEvent -ListLog * | Select-Object LogName, MaximumSizeInBytes


