name: Create Markdown and CSV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self repository
        uses: actions/checkout@v4

      - name: Checkout hayabusa-rules
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/hayabusa-rules
          path: hayabusa-rules

      - name: Run
        run: cargo run --release -- hayabusa-rules

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add *.md
          git add *.csv
          git add *.svg
          git commit -m "Automated update"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$(git log -1 --pretty=%B)" = "Automated update" ]; then
            git push origin main
          fi